# 使用说明 V3.7.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动
version: '3.7'
services:
  libao-redis:
    container_name: libao-redis
    image: redis:5.0.7
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    ports:
      - 16379:6379

  libao-admin:
    build:
      context: ./sgnbs-admin
    restart: always
    container_name: libao-admin
    image: libao-admin
    ports:
      - 18190:8080



